### ISSUE TITLE
Colab ModuleNotFoundError: No module named 'torchtext.legacy'

### ISSUE THREAD

**Issue by sharmer156** [pals-ttic/sjc#9]
when running Colab  it report error list:

Loading model from /content/drive/MyDrive/sjc/release/diffusion_ckpts/stable_diffusion/sd-v1-5.ckpt
Traceback (most recent call last):
  File "/content/drive/MyDrive/sjc/run_sjc.py", line 297, in <module>
    dispatch(SJC)
  File "/content/drive/MyDrive/sjc/my/config.py", line 76, in dispatch
    mod.run()
  File "/content/drive/MyDrive/sjc/run_sjc.py", line 77, in run
    model = getattr(self, family).make()
  File "/content/drive/MyDrive/sjc/run_img_sampling.py", line 39, in make
    model = StableDiffusion(**args)
  File "/content/drive/MyDrive/sjc/adapt_sd.py", line 89, in __init__
    self.model, H, W = load_sd1_model(self.checkpoint_root())
  File "/content/drive/MyDrive/sjc/adapt_sd.py", line 58, in load_sd1_model
    model = load_model_from_config(config, str(ckpt_fname))
  File "/content/drive/MyDrive/sjc/adapt_sd.py", line 34, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/apply_func.py", line 31, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'

**Comment by w-hc** [comment]
Thanks for the interest and encouragement. We will investigate.

**Comment by w-hc** [comment]
It's discussed in the other issue: `!pip install pytorch-lightning==1.8.3.post0`
